#! /bin/sh
# /etc/init.d/riegobot

### BEGIN INIT INFO
# Provides:          riegobot
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script de arranque del bot de riego
# Description:       Script de arrqnque del bot de riego
### END INIT INFO


# Dependiendo de los parámetros que se le pasen al programa se usa una opción u otra
case "$1" in
 start)
   echo "Arrancando riegobot"
   # Aquí hay que poner el programa que quieras arrancar automáticamente
   export TG_TOKEN=*******************
   export TG_CHAT_ID=***************

   /usr/local/bin/node /opt/riegoBot/app.js > /opt/riegoBot/riegobot.log
   ;;
 stop)
   echo "Deteniendo riegobot"

   ;;
 *)
   echo "Modo de uso: /etc/init.d/riegobot {start|stop}"
   exit 1
   ;;
esac

exit 0
